name: Notify

on:
  workflow_call:
    inputs:
      image_name:
        type: string
        description: Name of image for commit
        required: true
      tag:
        type: string
        description: New Docker image tag
        required: true
      digest:
        type: string
        description: Digest of the new Docker image
        required: true

jobs:
  notify:
    name: Notify Offshore_Operations_DAC of new release
    uses: gulfofmaine/odp-releaser/.github/workflows/notify.yml@52b11709c1fb73c142b24b62ce7a11ecb37f7da3
    permissions:
      contents: read
      pull-requests: read # ODP Releaser wants to figure out who made a PR
    with:
      tag: ${{ inputs.tag }}
      image_name: ${{ inputs.image_name }}
      digest: ${{ inputs.digest }}
      environment: notify
      verbosity: 3
    secrets:
      dispatch_app_id: ${{ secrets.GULFOFMAINE_ODP_DISPATCH_APP_ID }}
      dispatch_app_private_key: ${{ secrets.GULFOFMAINE_ODP_DISPATCH_PRIVATE_KEY }}
