name: Pipeline - Aveva Timeseries

on:
    push:
        branches:
            - main
        paths:
            - common/**
            - pipeline/aveva/**
            - .github/workflows/_shortsha.yml
            - .github/workflows/_build_image.yml
            - .github/workflows/pipeline_aveva.yml
    pull_request:
        paths:
            - common/**
            - pipeline/aveva/**
            - .github/workflows/_shortsha.yml
            - .github/workflows/_build_image.yml
            - .github/workflows/pipeline_aveva.yml
    workflow_dispatch:

jobs:
    shortsha:
        uses: ./.github/workflows/_shortsha.yml

    build_test_push:
        needs: [shortsha]
        uses: ./.github/workflows/_build_image.yml
        secrets: inherit
        with:
            working_directory: ./pipeline/aveva
            image_name: buoy_retriever_aveva
            image_tag: ${{ needs.shortsha.outputs.shortsha }}
            # push_image: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
            test_command: "pixi run pytest --cov=. --cov-report=xml:/tmp/coverage.xml --cov-report=term-missing --junitxml=/tmp/junit.xml -o junit_family=legacy"
            coverage_flags: aveva
            upload_tests: true
